[package]
name = "numerical_methods_rust"
version = "0.2.1"
authors = ["bencelaszlo <bencelaszlo@protonmail.com>"]

[dependencies]

[profile.dev]
opt-level = 3
codegen-units = 16
debug = 2

[profile.release]
opt-level = 3
codegen-units = 1
debug = false